name: Generate Snake Game

on:
  # 每 24 小时自动运行一次（格林威治时间 0 点，北京时间早上 8 点）
  schedule:
    - cron: "0 0 * * *"
  
  # 允许你在 GitHub 页面上点击按钮手动触发运行
  workflow_dispatch:
  
  # 当你向 main 分支推送代码时触发运行
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # 生成贪吃蛇动画 SVG
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: xinzhi5630
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      # 将生成的 SVG 推送到 output 分支进行独立托管
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
